joca_api/routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Recursoss
    Route::delete('recursosses/destroy', 'RecursossController@massDestroy')->name('recursosses.massDestroy');
    Route::resource('recursosses', 'RecursossController');

    // Trilha
    Route::delete('trilhas/destroy', 'TrilhaController@massDestroy')->name('trilhas.massDestroy');
    Route::resource('trilhas', 'TrilhaController');

    // Divugacoes
    Route::delete('divugacos/destroy', 'DivugacoesController@massDestroy')->name('divugacos.massDestroy');
    Route::resource('divugacos', 'DivugacoesController');

    // Cometario
    Route::delete('cometarios/destroy', 'CometarioController@massDestroy')->name('cometarios.massDestroy');
    Route::resource('cometarios', 'CometarioController');

    // Tipo De Recursos
    Route::delete('tipo-de-recursos/destroy', 'TipoDeRecursosController@massDestroy')->name('tipo-de-recursos.massDestroy');
    Route::resource('tipo-de-recursos', 'TipoDeRecursosController');

    // Tipo De Midia
    Route::delete('tipo-de-midia/destroy', 'TipoDeMidiaController@massDestroy')->name('tipo-de-midia.massDestroy');
    Route::resource('tipo-de-midia', 'TipoDeMidiaController');

    // Seguidores
    Route::delete('seguidores/destroy', 'SeguidoresController@massDestroy')->name('seguidores.massDestroy');
    Route::resource('seguidores', 'SeguidoresController');

    // Save
    Route::delete('saves/destroy', 'SaveController@massDestroy')->name('saves.massDestroy');
    Route::resource('saves', 'SaveController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

joca_api/app/Models/TipoDeRecurso.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TipoDeRecurso extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'tipo_de_recursos';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'description',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

joca_api/app/Http/Controllers/Admin/TipoDeRecursosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTipoDeRecursoRequest;
use App\Http\Requests\StoreTipoDeRecursoRequest;
use App\Http\Requests\UpdateTipoDeRecursoRequest;
use App\Models\TipoDeRecurso;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TipoDeRecursosController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('tipo_de_recurso_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tipoDeRecursos = TipoDeRecurso::all();

        return view('admin.tipoDeRecursos.index', compact('tipoDeRecursos'));
    }

    public function create()
    {
        abort_if(Gate::denies('tipo_de_recurso_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.tipoDeRecursos.create');
    }

    public function store(StoreTipoDeRecursoRequest $request)
    {
        $tipoDeRecurso = TipoDeRecurso::create($request->all());

        return redirect()->route('admin.tipo-de-recursos.index');
    }

    public function edit(TipoDeRecurso $tipoDeRecurso)
    {
        abort_if(Gate::denies('tipo_de_recurso_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.tipoDeRecursos.edit', compact('tipoDeRecurso'));
    }

    public function update(UpdateTipoDeRecursoRequest $request, TipoDeRecurso $tipoDeRecurso)
    {
        $tipoDeRecurso->update($request->all());

        return redirect()->route('admin.tipo-de-recursos.index');
    }

    public function show(TipoDeRecurso $tipoDeRecurso)
    {
        abort_if(Gate::denies('tipo_de_recurso_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.tipoDeRecursos.show', compact('tipoDeRecurso'));
    }

    public function destroy(TipoDeRecurso $tipoDeRecurso)
    {
        abort_if(Gate::denies('tipo_de_recurso_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tipoDeRecurso->delete();

        return back();
    }

    public function massDestroy(MassDestroyTipoDeRecursoRequest $request)
    {
        TipoDeRecurso::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

joca_api/resources/views/admin/tipoDeRecursos/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.tipoDeRecurso.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tipo-de-recursos.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.tipoDeRecurso.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tipoDeRecurso.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="description">{{ trans('cruds.tipoDeRecurso.fields.description') }}</label>
                <input class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" type="text" name="description" id="description" value="{{ old('description', '') }}">
                @if($errors->has('description'))
                    <div class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tipoDeRecurso.fields.description_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

joca_api/resources/views/admin/tipoDeRecursos/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.tipoDeRecurso.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tipo-de-recursos.update", [$tipoDeRecurso->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.tipoDeRecurso.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $tipoDeRecurso->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tipoDeRecurso.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="description">{{ trans('cruds.tipoDeRecurso.fields.description') }}</label>
                <input class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" type="text" name="description" id="description" value="{{ old('description', $tipoDeRecurso->description) }}">
                @if($errors->has('description'))
                    <div class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tipoDeRecurso.fields.description_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

joca_api/resources/views/admin/tipoDeRecursos/index.blade.php
@extends('layouts.admin')
@section('content')
@can('tipo_de_recurso_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.tipo-de-recursos.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.tipoDeRecurso.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.tipoDeRecurso.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-TipoDeRecurso">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.tipoDeRecurso.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.tipoDeRecurso.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.tipoDeRecurso.fields.description') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($tipoDeRecursos as $key => $tipoDeRecurso)
                        <tr data-entry-id="{{ $tipoDeRecurso->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $tipoDeRecurso->id ?? '' }}
                            </td>
                            <td>
                                {{ $tipoDeRecurso->name ?? '' }}
                            </td>
                            <td>
                                {{ $tipoDeRecurso->description ?? '' }}
                            </td>
                            <td>
                                @can('tipo_de_recurso_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.tipo-de-recursos.show', $tipoDeRecurso->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('tipo_de_recurso_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.tipo-de-recursos.edit', $tipoDeRecurso->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('tipo_de_recurso_delete')
                                    <form action="{{ route('admin.tipo-de-recursos.destroy', $tipoDeRecurso->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('tipo_de_recurso_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.tipo-de-recursos.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-TipoDeRecurso:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

joca_api/resources/views/admin/tipoDeRecursos/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.tipoDeRecurso.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tipo-de-recursos.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.tipoDeRecurso.fields.id') }}
                        </th>
                        <td>
                            {{ $tipoDeRecurso->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tipoDeRecurso.fields.name') }}
                        </th>
                        <td>
                            {{ $tipoDeRecurso->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tipoDeRecurso.fields.description') }}
                        </th>
                        <td>
                            {{ $tipoDeRecurso->description }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tipo-de-recursos.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection