joca_api/routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Recursoss
    Route::delete('recursosses/destroy', 'RecursossController@massDestroy')->name('recursosses.massDestroy');
    Route::resource('recursosses', 'RecursossController');

    // Trilha
    Route::delete('trilhas/destroy', 'TrilhaController@massDestroy')->name('trilhas.massDestroy');
    Route::resource('trilhas', 'TrilhaController');

    // Divugacoes
    Route::delete('divugacos/destroy', 'DivugacoesController@massDestroy')->name('divugacos.massDestroy');
    Route::resource('divugacos', 'DivugacoesController');

    // Cometario
    Route::delete('cometarios/destroy', 'CometarioController@massDestroy')->name('cometarios.massDestroy');
    Route::resource('cometarios', 'CometarioController');

    // Tipo De Recursos
    Route::delete('tipo-de-recursos/destroy', 'TipoDeRecursosController@massDestroy')->name('tipo-de-recursos.massDestroy');
    Route::resource('tipo-de-recursos', 'TipoDeRecursosController');

    // Tipo De Midia
    Route::delete('tipo-de-midia/destroy', 'TipoDeMidiaController@massDestroy')->name('tipo-de-midia.massDestroy');
    Route::resource('tipo-de-midia', 'TipoDeMidiaController');

    // Seguidores
    Route::delete('seguidores/destroy', 'SeguidoresController@massDestroy')->name('seguidores.massDestroy');
    Route::resource('seguidores', 'SeguidoresController');

    // Save
    Route::delete('saves/destroy', 'SaveController@massDestroy')->name('saves.massDestroy');
    Route::resource('saves', 'SaveController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

joca_api/app/Models/Seguidore.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Seguidore extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'seguidores';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'follow_id',
        'user_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function follow()
    {
        return $this->belongsTo(User::class, 'follow_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

joca_api/app/Http/Controllers/Admin/SeguidoresController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroySeguidoreRequest;
use App\Http\Requests\StoreSeguidoreRequest;
use App\Http\Requests\UpdateSeguidoreRequest;
use App\Models\Seguidore;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class SeguidoresController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('seguidore_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $seguidores = Seguidore::with(['follow', 'user'])->get();

        return view('admin.seguidores.index', compact('seguidores'));
    }

    public function create()
    {
        abort_if(Gate::denies('seguidore_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $follows = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $users = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.seguidores.create', compact('follows', 'users'));
    }

    public function store(StoreSeguidoreRequest $request)
    {
        $seguidore = Seguidore::create($request->all());

        return redirect()->route('admin.seguidores.index');
    }

    public function edit(Seguidore $seguidore)
    {
        abort_if(Gate::denies('seguidore_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $follows = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $users = User::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $seguidore->load('follow', 'user');

        return view('admin.seguidores.edit', compact('follows', 'seguidore', 'users'));
    }

    public function update(UpdateSeguidoreRequest $request, Seguidore $seguidore)
    {
        $seguidore->update($request->all());

        return redirect()->route('admin.seguidores.index');
    }

    public function show(Seguidore $seguidore)
    {
        abort_if(Gate::denies('seguidore_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $seguidore->load('follow', 'user');

        return view('admin.seguidores.show', compact('seguidore'));
    }

    public function destroy(Seguidore $seguidore)
    {
        abort_if(Gate::denies('seguidore_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $seguidore->delete();

        return back();
    }

    public function massDestroy(MassDestroySeguidoreRequest $request)
    {
        Seguidore::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

joca_api/resources/views/admin/seguidores/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.seguidore.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.seguidores.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="follow_id">{{ trans('cruds.seguidore.fields.follow') }}</label>
                <select class="form-control select2 {{ $errors->has('follow') ? 'is-invalid' : '' }}" name="follow_id" id="follow_id">
                    @foreach($follows as $id => $entry)
                        <option value="{{ $id }}" {{ old('follow_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('follow'))
                    <div class="invalid-feedback">
                        {{ $errors->first('follow') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.seguidore.fields.follow_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="user_id">{{ trans('cruds.seguidore.fields.user') }}</label>
                <select class="form-control select2 {{ $errors->has('user') ? 'is-invalid' : '' }}" name="user_id" id="user_id">
                    @foreach($users as $id => $entry)
                        <option value="{{ $id }}" {{ old('user_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('user'))
                    <div class="invalid-feedback">
                        {{ $errors->first('user') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.seguidore.fields.user_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

joca_api/resources/views/admin/seguidores/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.seguidore.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.seguidores.update", [$seguidore->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="follow_id">{{ trans('cruds.seguidore.fields.follow') }}</label>
                <select class="form-control select2 {{ $errors->has('follow') ? 'is-invalid' : '' }}" name="follow_id" id="follow_id">
                    @foreach($follows as $id => $entry)
                        <option value="{{ $id }}" {{ (old('follow_id') ? old('follow_id') : $seguidore->follow->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('follow'))
                    <div class="invalid-feedback">
                        {{ $errors->first('follow') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.seguidore.fields.follow_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="user_id">{{ trans('cruds.seguidore.fields.user') }}</label>
                <select class="form-control select2 {{ $errors->has('user') ? 'is-invalid' : '' }}" name="user_id" id="user_id">
                    @foreach($users as $id => $entry)
                        <option value="{{ $id }}" {{ (old('user_id') ? old('user_id') : $seguidore->user->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('user'))
                    <div class="invalid-feedback">
                        {{ $errors->first('user') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.seguidore.fields.user_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

joca_api/resources/views/admin/seguidores/index.blade.php
@extends('layouts.admin')
@section('content')
@can('seguidore_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.seguidores.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.seguidore.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.seguidore.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Seguidore">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.seguidore.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.seguidore.fields.follow') }}
                        </th>
                        <th>
                            {{ trans('cruds.seguidore.fields.user') }}
                        </th>
                        <th>
                            {{ trans('cruds.user.fields.email') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($seguidores as $key => $seguidore)
                        <tr data-entry-id="{{ $seguidore->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $seguidore->id ?? '' }}
                            </td>
                            <td>
                                {{ $seguidore->follow->name ?? '' }}
                            </td>
                            <td>
                                {{ $seguidore->user->name ?? '' }}
                            </td>
                            <td>
                                {{ $seguidore->user->email ?? '' }}
                            </td>
                            <td>
                                @can('seguidore_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.seguidores.show', $seguidore->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('seguidore_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.seguidores.edit', $seguidore->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('seguidore_delete')
                                    <form action="{{ route('admin.seguidores.destroy', $seguidore->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('seguidore_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.seguidores.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Seguidore:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

joca_api/resources/views/admin/seguidores/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.seguidore.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.seguidores.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.seguidore.fields.id') }}
                        </th>
                        <td>
                            {{ $seguidore->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.seguidore.fields.follow') }}
                        </th>
                        <td>
                            {{ $seguidore->follow->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.seguidore.fields.user') }}
                        </th>
                        <td>
                            {{ $seguidore->user->name ?? '' }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.seguidores.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection