joca_api/routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Recursoss
    Route::delete('recursosses/destroy', 'RecursossController@massDestroy')->name('recursosses.massDestroy');
    Route::resource('recursosses', 'RecursossController');

    // Trilha
    Route::delete('trilhas/destroy', 'TrilhaController@massDestroy')->name('trilhas.massDestroy');
    Route::resource('trilhas', 'TrilhaController');

    // Divugacoes
    Route::delete('divugacos/destroy', 'DivugacoesController@massDestroy')->name('divugacos.massDestroy');
    Route::resource('divugacos', 'DivugacoesController');

    // Cometario
    Route::delete('cometarios/destroy', 'CometarioController@massDestroy')->name('cometarios.massDestroy');
    Route::resource('cometarios', 'CometarioController');

    // Tipo De Recursos
    Route::delete('tipo-de-recursos/destroy', 'TipoDeRecursosController@massDestroy')->name('tipo-de-recursos.massDestroy');
    Route::resource('tipo-de-recursos', 'TipoDeRecursosController');

    // Tipo De Midia
    Route::delete('tipo-de-midia/destroy', 'TipoDeMidiaController@massDestroy')->name('tipo-de-midia.massDestroy');
    Route::resource('tipo-de-midia', 'TipoDeMidiaController');

    // Seguidores
    Route::delete('seguidores/destroy', 'SeguidoresController@massDestroy')->name('seguidores.massDestroy');
    Route::resource('seguidores', 'SeguidoresController');

    // Save
    Route::delete('saves/destroy', 'SaveController@massDestroy')->name('saves.massDestroy');
    Route::resource('saves', 'SaveController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

joca_api/app/Models/Trilha.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Trilha extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'trilhas';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'titulo',
        'status',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function recursos()
    {
        return $this->belongsToMany(Recursoss::class);
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

joca_api/app/Http/Controllers/Admin/TrilhaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTrilhaRequest;
use App\Http\Requests\StoreTrilhaRequest;
use App\Http\Requests\UpdateTrilhaRequest;
use App\Models\Recursoss;
use App\Models\Trilha;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TrilhaController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('trilha_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $trilhas = Trilha::with(['recursos'])->get();

        return view('admin.trilhas.index', compact('trilhas'));
    }

    public function create()
    {
        abort_if(Gate::denies('trilha_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $recursos = Recursoss::pluck('title', 'id');

        return view('admin.trilhas.create', compact('recursos'));
    }

    public function store(StoreTrilhaRequest $request)
    {
        $trilha = Trilha::create($request->all());
        $trilha->recursos()->sync($request->input('recursos', []));

        return redirect()->route('admin.trilhas.index');
    }

    public function edit(Trilha $trilha)
    {
        abort_if(Gate::denies('trilha_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $recursos = Recursoss::pluck('title', 'id');

        $trilha->load('recursos');

        return view('admin.trilhas.edit', compact('recursos', 'trilha'));
    }

    public function update(UpdateTrilhaRequest $request, Trilha $trilha)
    {
        $trilha->update($request->all());
        $trilha->recursos()->sync($request->input('recursos', []));

        return redirect()->route('admin.trilhas.index');
    }

    public function show(Trilha $trilha)
    {
        abort_if(Gate::denies('trilha_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $trilha->load('recursos');

        return view('admin.trilhas.show', compact('trilha'));
    }

    public function destroy(Trilha $trilha)
    {
        abort_if(Gate::denies('trilha_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $trilha->delete();

        return back();
    }

    public function massDestroy(MassDestroyTrilhaRequest $request)
    {
        Trilha::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

joca_api/resources/views/admin/trilhas/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.trilha.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.trilhas.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="titulo">{{ trans('cruds.trilha.fields.titulo') }}</label>
                <input class="form-control {{ $errors->has('titulo') ? 'is-invalid' : '' }}" type="text" name="titulo" id="titulo" value="{{ old('titulo', '') }}" required>
                @if($errors->has('titulo'))
                    <div class="invalid-feedback">
                        {{ $errors->first('titulo') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.trilha.fields.titulo_helper') }}</span>
            </div>
            <div class="form-group">
                <div class="form-check {{ $errors->has('status') ? 'is-invalid' : '' }}">
                    <input class="form-check-input" type="checkbox" name="status" id="status" value="1" required {{ old('status', 0) == 1 ? 'checked' : '' }}>
                    <label class="required form-check-label" for="status">{{ trans('cruds.trilha.fields.status') }}</label>
                </div>
                @if($errors->has('status'))
                    <div class="invalid-feedback">
                        {{ $errors->first('status') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.trilha.fields.status_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="recursos">{{ trans('cruds.trilha.fields.recursos') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('recursos') ? 'is-invalid' : '' }}" name="recursos[]" id="recursos" multiple>
                    @foreach($recursos as $id => $recurso)
                        <option value="{{ $id }}" {{ in_array($id, old('recursos', [])) ? 'selected' : '' }}>{{ $recurso }}</option>
                    @endforeach
                </select>
                @if($errors->has('recursos'))
                    <div class="invalid-feedback">
                        {{ $errors->first('recursos') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.trilha.fields.recursos_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

joca_api/resources/views/admin/trilhas/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.trilha.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.trilhas.update", [$trilha->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="titulo">{{ trans('cruds.trilha.fields.titulo') }}</label>
                <input class="form-control {{ $errors->has('titulo') ? 'is-invalid' : '' }}" type="text" name="titulo" id="titulo" value="{{ old('titulo', $trilha->titulo) }}" required>
                @if($errors->has('titulo'))
                    <div class="invalid-feedback">
                        {{ $errors->first('titulo') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.trilha.fields.titulo_helper') }}</span>
            </div>
            <div class="form-group">
                <div class="form-check {{ $errors->has('status') ? 'is-invalid' : '' }}">
                    <input class="form-check-input" type="checkbox" name="status" id="status" value="1" {{ $trilha->status || old('status', 0) === 1 ? 'checked' : '' }} required>
                    <label class="required form-check-label" for="status">{{ trans('cruds.trilha.fields.status') }}</label>
                </div>
                @if($errors->has('status'))
                    <div class="invalid-feedback">
                        {{ $errors->first('status') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.trilha.fields.status_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="recursos">{{ trans('cruds.trilha.fields.recursos') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('recursos') ? 'is-invalid' : '' }}" name="recursos[]" id="recursos" multiple>
                    @foreach($recursos as $id => $recurso)
                        <option value="{{ $id }}" {{ (in_array($id, old('recursos', [])) || $trilha->recursos->contains($id)) ? 'selected' : '' }}>{{ $recurso }}</option>
                    @endforeach
                </select>
                @if($errors->has('recursos'))
                    <div class="invalid-feedback">
                        {{ $errors->first('recursos') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.trilha.fields.recursos_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

joca_api/resources/views/admin/trilhas/index.blade.php
@extends('layouts.admin')
@section('content')
@can('trilha_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.trilhas.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.trilha.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.trilha.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Trilha">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.trilha.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.trilha.fields.titulo') }}
                        </th>
                        <th>
                            {{ trans('cruds.trilha.fields.status') }}
                        </th>
                        <th>
                            {{ trans('cruds.trilha.fields.recursos') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($trilhas as $key => $trilha)
                        <tr data-entry-id="{{ $trilha->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $trilha->id ?? '' }}
                            </td>
                            <td>
                                {{ $trilha->titulo ?? '' }}
                            </td>
                            <td>
                                <span style="display:none">{{ $trilha->status ?? '' }}</span>
                                <input type="checkbox" disabled="disabled" {{ $trilha->status ? 'checked' : '' }}>
                            </td>
                            <td>
                                @foreach($trilha->recursos as $key => $item)
                                    <span class="badge badge-info">{{ $item->title }}</span>
                                @endforeach
                            </td>
                            <td>
                                @can('trilha_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.trilhas.show', $trilha->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('trilha_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.trilhas.edit', $trilha->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('trilha_delete')
                                    <form action="{{ route('admin.trilhas.destroy', $trilha->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('trilha_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.trilhas.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Trilha:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

joca_api/resources/views/admin/trilhas/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.trilha.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.trilhas.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.trilha.fields.id') }}
                        </th>
                        <td>
                            {{ $trilha->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.trilha.fields.titulo') }}
                        </th>
                        <td>
                            {{ $trilha->titulo }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.trilha.fields.status') }}
                        </th>
                        <td>
                            <input type="checkbox" disabled="disabled" {{ $trilha->status ? 'checked' : '' }}>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.trilha.fields.recursos') }}
                        </th>
                        <td>
                            @foreach($trilha->recursos as $key => $recursos)
                                <span class="label label-info">{{ $recursos->title }}</span>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.trilhas.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection