joca_api/routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Recursoss
    Route::delete('recursosses/destroy', 'RecursossController@massDestroy')->name('recursosses.massDestroy');
    Route::resource('recursosses', 'RecursossController');

    // Trilha
    Route::delete('trilhas/destroy', 'TrilhaController@massDestroy')->name('trilhas.massDestroy');
    Route::resource('trilhas', 'TrilhaController');

    // Divugacoes
    Route::delete('divugacos/destroy', 'DivugacoesController@massDestroy')->name('divugacos.massDestroy');
    Route::resource('divugacos', 'DivugacoesController');

    // Cometario
    Route::delete('cometarios/destroy', 'CometarioController@massDestroy')->name('cometarios.massDestroy');
    Route::resource('cometarios', 'CometarioController');

    // Tipo De Recursos
    Route::delete('tipo-de-recursos/destroy', 'TipoDeRecursosController@massDestroy')->name('tipo-de-recursos.massDestroy');
    Route::resource('tipo-de-recursos', 'TipoDeRecursosController');

    // Tipo De Midia
    Route::delete('tipo-de-midia/destroy', 'TipoDeMidiaController@massDestroy')->name('tipo-de-midia.massDestroy');
    Route::resource('tipo-de-midia', 'TipoDeMidiaController');

    // Seguidores
    Route::delete('seguidores/destroy', 'SeguidoresController@massDestroy')->name('seguidores.massDestroy');
    Route::resource('seguidores', 'SeguidoresController');

    // Save
    Route::delete('saves/destroy', 'SaveController@massDestroy')->name('saves.massDestroy');
    Route::resource('saves', 'SaveController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

joca_api/app/Http/Controllers/Admin/TipoDeMidiaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTipoDeMidiumRequest;
use App\Http\Requests\StoreTipoDeMidiumRequest;
use App\Http\Requests\UpdateTipoDeMidiumRequest;
use App\Models\Recursoss;
use App\Models\TipoDeMidium;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TipoDeMidiaController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('tipo_de_midium_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tipoDeMidia = TipoDeMidium::with(['recursos'])->get();

        return view('admin.tipoDeMidia.index', compact('tipoDeMidia'));
    }

    public function create()
    {
        abort_if(Gate::denies('tipo_de_midium_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $recursos = Recursoss::pluck('title', 'id');

        return view('admin.tipoDeMidia.create', compact('recursos'));
    }

    public function store(StoreTipoDeMidiumRequest $request)
    {
        $tipoDeMidium = TipoDeMidium::create($request->all());
        $tipoDeMidium->recursos()->sync($request->input('recursos', []));

        return redirect()->route('admin.tipo-de-midia.index');
    }

    public function edit(TipoDeMidium $tipoDeMidium)
    {
        abort_if(Gate::denies('tipo_de_midium_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $recursos = Recursoss::pluck('title', 'id');

        $tipoDeMidium->load('recursos');

        return view('admin.tipoDeMidia.edit', compact('recursos', 'tipoDeMidium'));
    }

    public function update(UpdateTipoDeMidiumRequest $request, TipoDeMidium $tipoDeMidium)
    {
        $tipoDeMidium->update($request->all());
        $tipoDeMidium->recursos()->sync($request->input('recursos', []));

        return redirect()->route('admin.tipo-de-midia.index');
    }

    public function show(TipoDeMidium $tipoDeMidium)
    {
        abort_if(Gate::denies('tipo_de_midium_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tipoDeMidium->load('recursos');

        return view('admin.tipoDeMidia.show', compact('tipoDeMidium'));
    }

    public function destroy(TipoDeMidium $tipoDeMidium)
    {
        abort_if(Gate::denies('tipo_de_midium_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tipoDeMidium->delete();

        return back();
    }

    public function massDestroy(MassDestroyTipoDeMidiumRequest $request)
    {
        TipoDeMidium::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

joca_api/resources/views/admin/tipoDeMidia/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.tipoDeMidium.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tipo-de-midia.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="recursos">{{ trans('cruds.tipoDeMidium.fields.recursos') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('recursos') ? 'is-invalid' : '' }}" name="recursos[]" id="recursos" multiple>
                    @foreach($recursos as $id => $recurso)
                        <option value="{{ $id }}" {{ in_array($id, old('recursos', [])) ? 'selected' : '' }}>{{ $recurso }}</option>
                    @endforeach
                </select>
                @if($errors->has('recursos'))
                    <div class="invalid-feedback">
                        {{ $errors->first('recursos') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tipoDeMidium.fields.recursos_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

joca_api/resources/views/admin/tipoDeMidia/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.tipoDeMidium.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tipo-de-midia.update", [$tipoDeMidium->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="recursos">{{ trans('cruds.tipoDeMidium.fields.recursos') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('recursos') ? 'is-invalid' : '' }}" name="recursos[]" id="recursos" multiple>
                    @foreach($recursos as $id => $recurso)
                        <option value="{{ $id }}" {{ (in_array($id, old('recursos', [])) || $tipoDeMidium->recursos->contains($id)) ? 'selected' : '' }}>{{ $recurso }}</option>
                    @endforeach
                </select>
                @if($errors->has('recursos'))
                    <div class="invalid-feedback">
                        {{ $errors->first('recursos') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.tipoDeMidium.fields.recursos_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

joca_api/resources/views/admin/tipoDeMidia/index.blade.php
@extends('layouts.admin')
@section('content')
@can('tipo_de_midium_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.tipo-de-midia.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.tipoDeMidium.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.tipoDeMidium.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-TipoDeMidium">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.tipoDeMidium.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.tipoDeMidium.fields.recursos') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($tipoDeMidia as $key => $tipoDeMidium)
                        <tr data-entry-id="{{ $tipoDeMidium->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $tipoDeMidium->id ?? '' }}
                            </td>
                            <td>
                                @foreach($tipoDeMidium->recursos as $key => $item)
                                    <span class="badge badge-info">{{ $item->title }}</span>
                                @endforeach
                            </td>
                            <td>
                                @can('tipo_de_midium_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.tipo-de-midia.show', $tipoDeMidium->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('tipo_de_midium_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.tipo-de-midia.edit', $tipoDeMidium->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('tipo_de_midium_delete')
                                    <form action="{{ route('admin.tipo-de-midia.destroy', $tipoDeMidium->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('tipo_de_midium_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.tipo-de-midia.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-TipoDeMidium:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

joca_api/resources/views/admin/tipoDeMidia/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.tipoDeMidium.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tipo-de-midia.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.tipoDeMidium.fields.id') }}
                        </th>
                        <td>
                            {{ $tipoDeMidium->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tipoDeMidium.fields.recursos') }}
                        </th>
                        <td>
                            @foreach($tipoDeMidium->recursos as $key => $recursos)
                                <span class="label label-info">{{ $recursos->title }}</span>
                            @endforeach
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.tipo-de-midia.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection